Make neoforge build work - Minecraft client (neoforge) task doesn't work due to: java.lang.NoClassDefFoundError: org/quiltmc/parsers/json/gson/GsonWriter